// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmnUWSVTaFLh2QRUbtWmKYAo0sKlQd3MM',
    appId: '1:902696690885:web:06505b421be2345c647cac',
    messagingSenderId: '902696690885',
    projectId: 'ubuntusystem-940be',
    authDomain: 'ubuntusystem-940be.firebaseapp.com',
    storageBucket: 'ubuntusystem-940be.appspot.com',
    measurementId: 'G-ELS2WXQSYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOXFzT7CRyDVQqekNqzgSNAqBpg2wfyMg',
    appId: '1:902696690885:android:bde62413412975f8647cac',
    messagingSenderId: '902696690885',
    projectId: 'ubuntusystem-940be',
    storageBucket: 'ubuntusystem-940be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHztyk4NxO0tkysGjE79gRgKU69-9VU4g',
    appId: '1:902696690885:ios:6211a5081842be70647cac',
    messagingSenderId: '902696690885',
    projectId: 'ubuntusystem-940be',
    storageBucket: 'ubuntusystem-940be.appspot.com',
    iosBundleId: 'com.example.ubuntuSystem',
  );
}
